baseURL = "https://zumikiti-note.netlify.com/"
languageCode = "ja-jp"
title = "zumikiti note"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[taxonomies]
  series = "series"

[params]
    author = "zumikiti"
    avatar = "ribon.jpg"
    favicon = "ribon.ico"
    description = """
        このブログは、気ままに備忘録を書いていくブログです。
        もし、お仕事のご依頼がございましたら、ご連絡ください。
    """
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/hanlio"
    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/zumikiti"
    weight = 30

# [[menu.main]]
#     identifier = "email"
#     # name = "Email"
#     pre = "<i class='fa fa-envelope fa-lg'></i>"
#     url = "mailto:username@example.com"
#     weight = 40